# Generated by Django 4.2.4 on 2024-12-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='book',
            new_name='borrowed_book',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='user',
            new_name='borrowed_by_user',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='returned',
            new_name='is_returned',
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrow_for',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, '5 days'), (7, '7 days'), (10, '10 days'), (15, '15 days'), (30, '30 days')], null=True),
        ),
    ]
