# Generated by Django 4.2.4 on 2024-12-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_rename_book_borrow_borrowed_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_for',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 days'), (5, '5 days'), (7, '7 days'), (10, '10 days'), (15, '15 days'), (30, '30 days')], default=3),
        ),
    ]
