# Generated by Django 4.2.4 on 2024-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_borrow_borrow_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
