# Generated by Django 4.2.4 on 2024-12-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_borrow_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='created_at',
        ),
    ]
